# permissions for end users to edit podtrackers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podtracker
    app.kubernetes.io/managed-by: kustomize
  name: podtracker-editor-role
rules:
- apiGroups:
  - crd.example.com
  resources:
  - podtrackers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.example.com
  resources:
  - podtrackers/status
  verbs:
  - get
