# permissions for end users to view podtrackers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podtracker
    app.kubernetes.io/managed-by: kustomize
  name: podtracker-viewer-role
rules:
- apiGroups:
  - crd.example.com
  resources:
  - podtrackers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.example.com
  resources:
  - podtrackers/status
  verbs:
  - get
