apiVersion: crd.example.com/v1
kind: PodTracker
metadata:
  labels:
    app.kubernetes.io/name: podtracker
    app.kubernetes.io/managed-by: kustomize
  name: podtracker-sample
spec:
  # TODO(user): Add fields here
